name: Release artifacts

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Rename ref name
        uses: mad9000/actions-find-and-replace-string@2
        id: version
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.platform }}-artifacts
      - name: Archive Artifacts
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: MacRecoveryX-${{ steps.version.outputs.value }}-${{inputs.platform}}.zip
      - name: Artifacts Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: MacRecoveryX-${{ steps.version.outputs.value }}-${{inputs.platform}}.zip